live/routes/web.php
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('api/todo', ['uses' => 'TodoController@index']);
Route::post('api/todo', ['uses' => 'TodoController@store']);
Route::get('api/cashIn', ['uses' => 'TodoController@get_cashIn']);
Route::post('api/cashIn', ['uses' => 'TodoController@post_cashIn']);
Route::post('api/edit_cashIn/{id}', ['uses' => 'TodoController@edit_cashIn']);
Route::post('api/delete_cashIn/{id}', ['uses' => 'TodoController@delete_cashIn']);

Route::get('api/cashOut', ['uses' => 'TodoController@get_cashOut']);
Route::post('api/cashOut', ['uses' => 'TodoController@post_cashOut']);
Route::post('api/edit_cashOut/{id}', ['uses' => 'TodoController@edit_cashOut']);
Route::post('api/delete_cashOut/{id}', ['uses' => 'TodoController@delete_cashOut']);

Route::get('api/dhaFees', ['uses' => 'TodoController@get_dhaFees']);
Route::post('api/dhaFees', ['uses' => 'TodoController@post_dhaFees']);
Route::post('api/edit_dhaFees/{id}', ['uses' => 'TodoController@edit_dhaFees']);
Route::post('api/delete_dhaFees/{id}', ['uses' => 'TodoController@delete_dhaFees']);

/*Installment Api Routes*/
Route::get('api/userInstallment/{id}', ['uses' => 'TodoController@get_userInstallment']);
Route::post('api/userInstallment/{id}/delete/{ins_id}', ['uses' => 'TodoController@delete_userInstallment']);
Route::post('api/userInstallment',['uses'=>'TodoController@post_userInstallment']);


/*service charge routes*/
Route::get('api/addServiceCharge', ['uses' => 'TodoController@get_ServiceCharge']);
Route::post('api/addServiceCharge', ['uses' => 'TodoController@post_ServiceCharge']);
Route::post('api/editServiceCharge/{id}', ['uses' => 'TodoController@edit_ServiceCharge']);
Route::post('api/deleteServiceCharge/{id}', ['uses' => 'TodoController@delete_ServiceCharge']);


Route::get('api/addNewDhaMcqOffer', ['uses' => 'TodoController@get_dhaMcqOffer']);
Route::post('api/addNewDhaMcqOffer', ['uses' => 'TodoController@post_dhaMcqOffer']);

/*Routes for enquiry by Them*/
Route::get('api/addEnquiryByThem', ['uses' => 'TodoController@get_EnquiryByThem']);
Route::get('api/todayEnquiryByThem', ['uses' => 'TodoController@today_EnquiryByThem']);
Route::post('api/addEnquiryByThem', ['uses' => 'TodoController@post_EnquiryByThem']);
Route::post('api/editEnquiryByThem/{id}', ['uses' => 'TodoController@edit_EnquiryByThem']);
Route::post('api/deleteEnquiryByThem/{id}', ['uses' => 'TodoController@delete_EnquiryByThem']);

/*Routes for enquiry In Office*/
Route::get('api/addEnquiryInOffice', ['uses' => 'TodoController@get_EnquiryInOffice']);
Route::get('api/todayEnquiryInOffice', ['uses' => 'TodoController@today_EnquiryInOffice']);
Route::post('api/addEnquiryInOffice', ['uses' => 'TodoController@post_EnquiryInOffice']);
Route::post('api/editEnquiryInOffice/{id}', ['uses' => 'TodoController@edit_EnquiryInOffice']);
Route::post('api/deleteEnquiryInOffice/{id}', ['uses' => 'TodoController@delete_EnquiryInOffice']);

/*Routes for enquiry by us*/
Route::get('api/addEnquiryByUs', ['uses' => 'TodoController@get_EnquiryByUs']);
Route::get('api/todayEnquiryByUs', ['uses' => 'TodoController@today_EnquiryByUs']);
Route::post('api/addEnquiryByUs', ['uses' => 'TodoController@post_EnquiryByUs']);
Route::post('api/editEnquiryByUs/{id}', ['uses' => 'TodoController@edit_EnquiryByUs']);
Route::post('api/deleteEnquiryByUs/{id}', ['uses' => 'TodoController@delete_EnquiryByUs']);

Route::get('api/addServiceManageService', ['uses' => 'TodoController@get_service']);
Route::post('api/addServiceManageService', ['uses' => 'TodoController@post_service']);
Route::get('api/addStudent', ['uses' => 'TodoController@get_student']);
Route::post('api/addStudent', ['uses' => 'TodoController@post_student']);
Route::get('api/addTransaction', ['uses' => 'TodoController@get_transaction']);
Route::post('api/addTransaction', ['uses' => 'TodoController@post_transaction']);
Route::post('api/uploadImage', ['uses' => 'TodoController@uploadImage']);

Route::get('api/cmsInformation', ['uses' => 'TodoController@cmsInformation']);



Route::get('/', 'backend\DashboardController@getLogin');
//Route::get('/login', 'backend\DashboardController@getLogin');
Route::get('admin', 'backend\DashboardController@getLogin');
//by harry
Route::get('/login', array('as' => 'login', 'uses' => 'backend\DashboardController@getLogin'));
Route::get('/logout', array('as' => 'logout', 'uses' => 'backend\DashboardController@getLogout'));
Route::post('/logout', array('as' => 'logout', 'uses' => 'backend\DashboardController@getLogout'));
Route::post('admin', 'backend\DashboardController@postLogin');

Route::get('/{id}','backend\DashboardController@notFound');

Route::group(['middleware'=>['auth']],function(){
    Route::get('admin/expensestype', 'backend\DashboardController@getExpenses');
    Route::post('admin/expensestype', 'backend\DashboardController@postExpenses');
    Route::get('admin/logout', 'backend\DashboardController@getLogout');

    Route::get('admin/{user_id}/dashboard','backend\DashboardController@index');
    Route::get('admin/dashboard','backend\DashboardController@index');
    Route::resource('admin/user','backend\UserController');
    Route::resource('admin/installment','backend\DhaInstallmentController');
    Route::resource('admin/installmentservice','backend\ServiceInstallmentController');
    Route::get('admin/serviceinvoice/{id}','backend\ServiceInstallmentController@viewinvoice');
    Route::post('admin/installment/{id}','backend\DhaInstallmentController@create');
    Route::post('admin/installmentservice/{id}','backend\ServiceInstallmentController@create');
    Route::post('admin/installmentservice/{id}','backend\ServiceInstallmentController@create');
    Route::delete('admin/installmentservice/{id}','backend\ServiceInstallmentController@destroy');
    Route::post('admin/installment','backend\DhaInstallmentController@store');
    Route::delete('admin/installment/{id}','backend\DhaInstallmentController@destroy');
    Route::get('admin/viewinvoice/{id}','backend\DhaInstallmentController@viewinvoice');
    // show report
    Route::post('admin/dhainstallment','backend\DHAController@createdhainstallment');

    Route::get('admin/edit/{id}','backend\DhaController@edit');
    Route::get('admin/editservicecharge/{id}','backend\ServiceChargeController@edit');
    Route::post('admin/json','backend\JsonController@json');
    Route::resource('admin/service_charge','backend\ServiceChargeController');


    Route::resource('admin/cash_in','backend\cash_inController');

    Route::resource('admin/cash_out','backend\CashOutController');

    Route::resource('admin/dha','backend\DHAController');
    Route::get('admin/dhashow/{id}','backend\DHAController@show');
    Route::resource('admin/enquiry','backend\EnquiryController');
    Route::resource('admin/enquirybythem','backend\EnquiryByThemController');
    Route::resource('admin/enquiryinoffice','backend\EnquiryInOFficeController');
    Route::get('admin/dhainvoice','backend\InvoiceController@dhainvoice');
    Route::get('admin/serviceinvoice','backend\InvoiceController@serviceinvoice');
    Route::resource('admin/reminder','backend\ReminderController');
    Route::resource('admin/service','backend\ServiceController');
    Route::resource('admin/student','backend\StudentController');
    Route::resource('admin/transaction','backend\TransactionController');
    Route::resource('admin/offer','backend\OfferController');
    Route::resource('admin/status','backend\StatusController');
    Route::get('admin/viewstatus','backend\ViewStatusController@show');
    Route::get('admin/statuss','backend\StatusController@createdhastatus');
    Route::get('admin/dhastatus','backend\StatusController@createdhastatus');
    Route::post('admin/dhastatuss','backend\StatusController@postdhastatus');
    // Route::resource('admin/dataflow','DataFlowStatusController');
    Route::resource('admin/dataflow','backend\DataFlowStatusController');
    Route::get('admin/dataflowform','backend\DataFlowStatusController@create');
    Route::post('admin/dataflowform','backend\DataFlowStatusController@store');
    Route::resource('admin/examstatus','backend\ExamStatusController');
    Route::get('admin/examstatusform','backend\ExamStatusController@create');
    Route::post('admin/examstatusform','backend\ExamStatusController@store');
    Route::post('admin/contact','backend\OfferController@postOffer');
// CanditatesREport

    Route::resource('admin/candidates_report','backend\CandidatesReportController'); 

   


    // newsletter
    Route::get('admin/news','backend\NewsLetterController@contact');
    Route::post('admin/news','backend\NewsLetterController@postcontact');
    // CMS
    Route::get('admin/cms','backend\cmsController@index');
    Route::get('updatePassword', 'backend\DashboardController@updatePassword');
    Route::get('admin/{username}/profile', 'backend\DashboardController@profile');
    Route::post('/profilepost', 'backend\DashboardController@updatePassword')->name('profilepost');
    Route::post('/profilepost/{id}', 'backend\DashboardController@editInfo');
    Route::post('updateProfile','backend\DashboardController@updateProfile');
    // show report
    Route::post('admin/report','backend\DashboardController@getReport');
    Route::post('admin/nepalicalender','backend\DashboardController@nepalidate');
    Route::post('admin/nepali','backend\DashboardController@nepali');
    Route::post('admin/englishDate','backend\DashboardController@englishDate');
    Route::post('admin/nepalidate2','backend\DashboardController@nepaliDate2');
    Route::post('admin/englishdate2','backend\DashboardController@englishDate2');
    Route::get('admin/{id}','backend\DashboardController@notFound');
    Route::get('admin/{id}/{ids}','backend\DashboardController@notFound');



});

/*Route::get('/', funcbtion () {
    return view('welcome');

live/app/Http/Controllers/backend/StatusController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DhaFees;
use App\DhaStatus;
use App\DataflowStatus;
use DB;
use App\User;
class StatusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $status;
    public function __construct(DhaStatus $status){
        $this->status = $status;
    }
    public function index()
    {
        $status = DhaStatus::all();
        $dha_fees=DhaFees::pluck('name','id');
        return view('officio.status.index',compact('status','dha_fees'))->with('title','User Status');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\ResponseC
     */
    public function create()
    {
        // $dhaFees_detail=DhaFees::all();
        $dhafees=DhaFees::pluck('name','id');
        return view('officio.status.create',compact('dhafees'))->with('title','Create User Status');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
     if(!$request->dha_id){
        return false;
    }
    
    $this->validate($request, [
        'dha_id' => 'required',


        ]);
    $input = $request->all();
    if ($input) {
       DhaStatus::create($input);
       session()->flash('message', 'User Status  Created.');
       return redirect('admin/dhastatus');
            // return view('')
   }
}
public function createdhastatus(Request $request)
{

    $type=DhaStatus::with(array('dhafees'=>function($query){
        $query->select('id','name','applied_for');
    }))->get();

   // return($type[0]->dhafees->applied_for);
  
  if($request->dha_id){
      $dataflow=DataflowStatus::all();
      
      $dha_id=$request->dha_id;
      return view('officio.status.createdhastatus',compact('dataflow','dha_id','type'))->with('title','Create User Status');

      
  }
  
}

public function postdhastatus(Request $request){

   $this->validate($request, [
    'email' => 'required',
    'username' => 'required',
    'password' => 'required',


    ]);

   $input = $request->all();
// $input['password']=bcrypt($request->password);
   if ($input) {
       DhaStatus::create($input);
       session()->flash('message', 'User Status  Created.');
       return redirect('admin/status');
   }   
}
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $status = DhaStatus::with('dhafees')->get();
//          return $status;
       
       return view('officio.status.show',compact('status'))->with('title','User Status'); 
   }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dhastatus = DhaStatus::find($id);
       // $dhastatus=DhaStatus::with('dhafees')->where('id',$id)->get();
        $dha_id=DhaStatus::with('dhafees')->where('id',$id)->get();
        return view('officio.status.editdha',compact('dhastatus','dha_id'))->with('title','Edit User Status');
    }

    /**
     * Update the specified rescashOutource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'email' => 'required',
            'username' => 'required',
            'password' => 'required',
            
            ]);
        $dhastatus = DhaStatus::find($id);
        $input = $request->all();
        $dhastatus->update($input);
        session()->flash('message', 'Dha Status Updated.');
        return redirect('admin/status');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!request()->ajax()){
            return false;
        }

        DhaStatus::find($id)->delete();


        session()->flash('message', 'DHA Profile Deleted.');

        return response()->json(array(
            'status' => 'success',
            ));
    }
}

live/resources/views/officio/status/create.blade.php
@extends('officio.main')
@section('title','add User Status')

@section('content')
{{----}}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
      Create Dubai Health Authority(DHA) Profile
    </h1>
</section>
@include('officio.flash.message')


<section class="content">
   <div class="row">
    <div class="col-md-12">

        {{--@include('flash.message')--}}
        {{--@include('errors.list')--}}

        <!-- Horizontal Form -->
        <div class="box box-info">
            <!-- form start -->
            <div class="box-body">
                <div class="row">
                  <div class="col-md-8">
                    {{ Form::open(['url'=>'admin/statuss', 'method'=>'GET', 'class' => 'form-horizontal','enctype'=>'multipart/form-data' ]) }}

                    @include('officio.status.form')
                    <div class="text-right border-top">
                        <button type="submit" class="btn btn-warning">Create Profile</button>
                    </div>
                    {{ form::close() }}
                </div>
            </div>
        </div>
    </div><!-- /.box -->


</div>
</section>
  
@stop

live/resources/views/officio/status/dataflowform.blade.php
  
         
 @if(Request::segment(4)!='edit')   
          <input type="hidden" name="dha_id" value="{{$dha_id}}" >
          @endif
<div class="box-body">
<div class="form-group" {{ $errors->has('passport_no') ? ' has-error' : ''  }}>    <label for="passport_no" class="col-sm-2 control-label">Passport Number:<span class=help-block"
	style="color: #b30000">&nbsp;* </span></label>

	<div class="col-sm-8">
		{!! Form::text('passport_no', null , ['class'=> 'form-control', 'placeholder' => ' Passport No', 'id'=>"passport_no"]) !!}

		@if ($errors->has('passport_no'))
		<span class="help-block">
			<strong> {{ $errors->first('passport_no') }}</strong>
		</span>
		@endif

	</div>
</div>      



<div class="form-group" {{ $errors->has('dha_ref_no') ? ' has-error' : ''}}>     <label for="dha_ref_no" class="col-sm-2 control-label">DHA Reference Number:<span class=help-block"
	style="color: #b30000">&nbsp;* </span></label>

	<div class="col-sm-8">
		{!! Form::text('dha_ref_no', null , ['class'=> 'form-control', 'placeholder' => ' DHA Reference No', 'id'=>"dha_ref_no"]) !!}

		@if ($errors->has('dha_ref_no'))
		<span class="help-block">
			<strong> {{ $errors->first('dha_ref_no') }}</strong>
		</span>
		@endif

	</div>
</div> 


<div class="form-group" {{ $errors->has('barcode_no') ? ' has-error' : ''}}>     <label for="barcode_no" class="col-sm-2 control-label">Dataflow Barcode Number:<span class=help-block"
	style="color: #b30000">&nbsp;* </span></label>

	<div class="col-sm-8">
		{!! Form::text('barcode_no', null , ['class'=> 'form-control', 'placeholder' => ' Barcode no', 'id'=>"barcode_no"]) !!}

		@if ($errors->has('barcode_no'))
		<span class="help-block">
			<strong> {{ $errors->first('barcode_no') }}</strong>
		</span>
		@endif

	</div>
</div> 





<div class="form-group" {{ $errors->has('remarks') ? ' has-error' : ''}}>      <label for="remarks" class="col-sm-2 control-label">Remarks:<span class=help-block"
	style="color: #b30000">&nbsp;* </span></label>

	<div class="col-sm-8">
		{!! Form::textarea('remarks', null , ['class'=> 'form-control', 'placeholder' => ' remarks', 'id'=>"remarks"]) !!}

		@if ($errors->has('remarks'))
		<span class="help-block">
			<strong> {{ $errors->first('remarks') }}</strong>
		</span>
		@endif

	</div>
</div>                

 <div class="form-group">
    {{Form::label('status','Status:',['class'=>'col-sm-2 control-label'])}}
        <div class="col-sm-8">
                    {{Form::radio('status',"1","1")}}{{Form::label('1','Active')}}
                    {{Form::radio('status',"0")}}{{Form::label('0','Inactive')}}


        </div>
    </div>
	</div>

live/resources/views/officio/status/editdataflow.blade.php
@extends('officio.main')


@section('content')
{{----}}
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Edit Data Flow Status
    </h1>
</section>
@include('officio.flash.message')

<section class="content">
    {!! Form::model($dataflow, [
        'route' => ['dataflow.update', $dataflow->id],
        'class' => 'form-horizontal',
        'method'=> 'PUT'
    ])
!!}

    <div class="row">
        <div class="col-md-10">
            @include('officio.status.dataflowform')
        </div>
    </div>

    <div class="text-right border-top">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>



    {!! Form::close() !!}

</section>
@stop

live/resources/views/officio/status/index.blade.php
@extends('officio.main')
@section('title','Cash Out')
@section('content')
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
       
         <span>
                <a href="{{ url('admin/status/create') }}">
                    <button type="button" class="btn btn-primary" id="viewbtn">
                        Create User Status
                    </button>
                </a>
        </span>
    </h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">

            @include('officio.flash.message')

            <div class="box">
                <div class="box-body">
                    <div class="table-reponsive">
                        <table id="example1" class="table table-bordered table-striped user-list">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Status</th>
                                <th>Action</th>
                             
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                                $i=1;
                              


                            ?>
                            @foreach($status as $type)
                                <tr>
                                    <td>{{ $i++ }}</td>
                              <td>
                                          <?php
                                          $roleId = $type->dha_id;
                                         // $roleId = array_filter($value->dropdown_id,function($x){ return !empty($x); });
                                            $role = \App\DhaFees::where('id',$roleId)->first();

                                            if(empty($role)){
                                                echo 'N/A';
                                            }
                                            else{
                                                echo $role->name;
                                            }
                                            //dd($role);
                                        ?>

                                       
                                  </td>
                                   
                                
                                        
                                   
                                
                                  
                                    <td>
                                        @if($type->status == 1)
                                            Active
                                        @else
                                            InActive
                                        @endif
                                    </td>

                                    <td>

                                        <a type="button" type="button" class="btn btn-primary btn-sm"
                                                href="{{ route('status.edit', array($type->id)) }}">
                                            <i class="flaticon-edit"></i>
                                        </a>

                                        <form action="{{ route('status.destroy', array($type->id)) }}"
                                              method="DELETE" class="delete-user-form">
                                            {!! csrf_field() !!}

                                            <button type="submit" class="btn btn-sm btn-danger">
                                                <i class="flaticon-delete-button"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
</tbody>

                        </table>
                    </div>
                </div><!-- /.box-body
            </div><!-- /.box -->
        </div><!-- /.col -->

    </div><!-- /.row -->
</section><!-- /.content -->

<script>
    $(function () {
        $('#example1').DataTable({
            "pageLength": 100,
            "dom": '<"top"pfl<"clear">>rt<"bottom"p<"clear">>'
        });
    });
</script>

@stop

live/resources/views/officio/status/show.blade.php
@extends('officio.main')
<!-- @section('title','add Dataflow Status') -->

@section('content')
{{----}}
<link rel="stylesheet" href="{{URL::to('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css')}}">
<script src="{{URL::to('https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js')}}"></script>
<script src="{{URL::to('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js')}}"></script>



<section class="content-header">

</section>
<div class="container">


  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">DHA Status</a></li>
    <li><a data-toggle="tab" href="#menu1">Data Flow Status</a></li>
    <li><a data-toggle="tab" href="#menu2">Exam Status</a></li>

  </ul>


  <!--  -->

  <section class="content">
    <div class="row">
      <div class="col-xs-12">

        @include('officio.flash.message')

        <div class="box">
          <div class="box-body">
            <div class="table-reponsive">

              <div class="tab-content">
                <div id="home" class="tab-pane fade in active">

                  <h3>DHA Status</h3>


                  <table id="example1" class="table table-bordered table-striped user-list">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Applied For</th>
                        <th>Email</th>
                        <th>Username</th>
                        <th>Password</th>
                        <th>Action</th>

                      </tr>
                    </thead>
                    <tbody>
                      <?php
                      $i=1;
                      ?>
                      @foreach($status as $type)
                      <?php
                      ?>
                      <tr>
                        <td>{{ $i++ }}</td>

                        <td>{{ $type->dhafees()->first()->name}}</td>
                        <td>{{ $type->dhafees()->first()->applied_for}}</td>
                        <td>{{ $type->email}}</td>
                        <td>{{ $type->username}}</td>
                        <td>{{ $type->password}}</td>
                        <td>

                          <a type="button" type="button" class="btn btn-primary btn-sm"
                          href="{{ route('status.edit', array($type->id)) }}">
                          <i class="flaticon-edit"></i>
                        </a>

                        <form action="{{ route('status.destroy', array($type->id)) }}"
                          method="DELETE" class="delete-user-form">
                          {!! csrf_field() !!}

                          <button type="submit" class="btn btn-sm btn-danger">
                            <i class="flaticon-delete-button"></i>
                          </button>

                        </form>
                      </td>


                    </tr>
                  </tbody>

                  @endforeach
                </table>

              </div>
              <div id="menu1" class="tab-pane fade">

               <h3>Data Flow Status</h3>


               <table id="example1" class="table table-bordered table-striped user-list">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Applied For</th>
                    <th>Passport No.</th>
                    <th>DHA Reference No.</th>
                    <th>Barcode No.</th>
                    <th>Remarks</th>

                    <th>Action</th>

                  </tr>
                </thead>
                <tbody>
                  <?php
                  $i=1;
                  ?>
                  @foreach($dataflow as $type)
                  <tr>
                    <td>{{ $i++ }}</td>

                    <td>{{ $type->dhafees()->first()->name }}</td>
                    <td>{{ $type->dhafees()->first()->applied_for}}</td>
                    <td>{{ $type->passport_no}}</td>
                    <td>{{ $type->dha_ref_no}}</td>
                    <td>{{ $type->barcode_no}}</td>                                                        
                    <td>{{ $type->remarks}}</td>
                    <td>

                      <a type="button" type="button" class="btn btn-primary btn-sm"
                      href="{{ route('dataflow.edit', array($type->id)) }}">
                      <i class="flaticon-edit"></i>
                    </a>

                    <form action="{{ route('dataflow.destroy', array($type->id)) }}"
                      method="DELETE" class="delete-user-form">
                      {!! csrf_field() !!}

                      <button type="submit" class="btn btn-sm btn-danger">
                        <i class="flaticon-delete-button"></i>
                      </button>

                    </form>
                  </td>


                </tr>
              </tbody>

              @endforeach
            </table>


          </div>

          <div id="menu2" class="tab-pane fade">
            <h3>Add Exam Status</h3>
            <table id="example1" class="table table-bordered table-striped user-list">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Applied For</th>
                  <th style="width: 90px;">Prefered Date From</th>

                  <th style="width: 90px;">Prefered Date To</th>
                  <th>Booked Date</th>
                  <th>DHA/MCQ Status</th>
                  <th>DHA Status</th>
                  <th>Eligibility</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <?php
                $i=1;
                ?>
                @foreach($examstatus as $type)
                <?php
                ?>
                <tr>
                  <td>{{ $i++ }}</td>

                  <td>{{ $type->dhafees()->first()->name}}</td>
                  <td>{{ $type->dhafees()->first()->applied_for}}</td>
                  <td>{{ $type->preferred_date_from}}</td>
                  <td>{{ $type->preferred_date_to}}</td>



                  <td>{{ $type->exam_date_booked}}</td>

                  <td>@if($type->dhamcq==1)
                    Pass
                    @else
                    Fail
                    @endif
                  </td>
                  

                  <td> @if($type->dha_status==1)
                    Pass
                    @else
                    Fail
                    @endif
                  </td>

                  <td> @if($type->eligibility==1)
                    Yes
                    @else
                    No
                    @endif
                  </td>
                  <td>

                    <a type="button" type="button" class="btn btn-primary btn-sm"
                    href="{{ route('examstatus.edit', array($type->id)) }}">
                    <i class="flaticon-edit"></i>
                  </a>

                  <form action="{{ route('examstatus.destroy', array($type->id)) }}"
                    method="DELETE" class="delete-user-form">
                    {!! csrf_field() !!}

                    <button type="submit" class="btn btn-sm btn-danger">
                      <i class="flaticon-delete-button"></i>
                    </button>

                  </form>
                </td>


              </tr>
            </tbody>

            @endforeach
          </table>

        </div>
      </div>

    </div>
  </div><!-- /.box-body -->
</div><!-- /.box -->
</div><!-- /.col -->

</div><!-- /.row -->

</section>

@stop