live/routes/web.php
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('api/todo', ['uses' => 'TodoController@index']);
Route::post('api/todo', ['uses' => 'TodoController@store']);
Route::get('api/cashIn', ['uses' => 'TodoController@get_cashIn']);
Route::post('api/cashIn', ['uses' => 'TodoController@post_cashIn']);
Route::post('api/edit_cashIn/{id}', ['uses' => 'TodoController@edit_cashIn']);
Route::post('api/delete_cashIn/{id}', ['uses' => 'TodoController@delete_cashIn']);

Route::get('api/cashOut', ['uses' => 'TodoController@get_cashOut']);
Route::post('api/cashOut', ['uses' => 'TodoController@post_cashOut']);
Route::post('api/edit_cashOut/{id}', ['uses' => 'TodoController@edit_cashOut']);
Route::post('api/delete_cashOut/{id}', ['uses' => 'TodoController@delete_cashOut']);

Route::get('api/dhaFees', ['uses' => 'TodoController@get_dhaFees']);
Route::post('api/dhaFees', ['uses' => 'TodoController@post_dhaFees']);
Route::post('api/edit_dhaFees/{id}', ['uses' => 'TodoController@edit_dhaFees']);
Route::post('api/delete_dhaFees/{id}', ['uses' => 'TodoController@delete_dhaFees']);

/*Installment Api Routes*/
Route::get('api/userInstallment/{id}', ['uses' => 'TodoController@get_userInstallment']);
Route::post('api/userInstallment/{id}/delete/{ins_id}', ['uses' => 'TodoController@delete_userInstallment']);
Route::post('api/userInstallment',['uses'=>'TodoController@post_userInstallment']);


/*service charge routes*/
Route::get('api/addServiceCharge', ['uses' => 'TodoController@get_ServiceCharge']);
Route::post('api/addServiceCharge', ['uses' => 'TodoController@post_ServiceCharge']);
Route::post('api/editServiceCharge/{id}', ['uses' => 'TodoController@edit_ServiceCharge']);
Route::post('api/deleteServiceCharge/{id}', ['uses' => 'TodoController@delete_ServiceCharge']);


Route::get('api/addNewDhaMcqOffer', ['uses' => 'TodoController@get_dhaMcqOffer']);
Route::post('api/addNewDhaMcqOffer', ['uses' => 'TodoController@post_dhaMcqOffer']);

/*Routes for enquiry by Them*/
Route::get('api/addEnquiryByThem', ['uses' => 'TodoController@get_EnquiryByThem']);
Route::get('api/todayEnquiryByThem', ['uses' => 'TodoController@today_EnquiryByThem']);
Route::post('api/addEnquiryByThem', ['uses' => 'TodoController@post_EnquiryByThem']);
Route::post('api/editEnquiryByThem/{id}', ['uses' => 'TodoController@edit_EnquiryByThem']);
Route::post('api/deleteEnquiryByThem/{id}', ['uses' => 'TodoController@delete_EnquiryByThem']);

/*Routes for enquiry In Office*/
Route::get('api/addEnquiryInOffice', ['uses' => 'TodoController@get_EnquiryInOffice']);
Route::get('api/todayEnquiryInOffice', ['uses' => 'TodoController@today_EnquiryInOffice']);
Route::post('api/addEnquiryInOffice', ['uses' => 'TodoController@post_EnquiryInOffice']);
Route::post('api/editEnquiryInOffice/{id}', ['uses' => 'TodoController@edit_EnquiryInOffice']);
Route::post('api/deleteEnquiryInOffice/{id}', ['uses' => 'TodoController@delete_EnquiryInOffice']);

/*Routes for enquiry by us*/
Route::get('api/addEnquiryByUs', ['uses' => 'TodoController@get_EnquiryByUs']);
Route::get('api/todayEnquiryByUs', ['uses' => 'TodoController@today_EnquiryByUs']);
Route::post('api/addEnquiryByUs', ['uses' => 'TodoController@post_EnquiryByUs']);
Route::post('api/editEnquiryByUs/{id}', ['uses' => 'TodoController@edit_EnquiryByUs']);
Route::post('api/deleteEnquiryByUs/{id}', ['uses' => 'TodoController@delete_EnquiryByUs']);

Route::get('api/addServiceManageService', ['uses' => 'TodoController@get_service']);
Route::post('api/addServiceManageService', ['uses' => 'TodoController@post_service']);
Route::get('api/addStudent', ['uses' => 'TodoController@get_student']);
Route::post('api/addStudent', ['uses' => 'TodoController@post_student']);
Route::get('api/addTransaction', ['uses' => 'TodoController@get_transaction']);
Route::post('api/addTransaction', ['uses' => 'TodoController@post_transaction']);
Route::post('api/uploadImage', ['uses' => 'TodoController@uploadImage']);

Route::get('api/cmsInformation', ['uses' => 'TodoController@cmsInformation']);



Route::get('/', 'backend\DashboardController@getLogin');
//Route::get('/login', 'backend\DashboardController@getLogin');
Route::get('admin', 'backend\DashboardController@getLogin');
//by harry
Route::get('/login', array('as' => 'login', 'uses' => 'backend\DashboardController@getLogin'));
Route::get('/logout', array('as' => 'logout', 'uses' => 'backend\DashboardController@getLogout'));
Route::post('/logout', array('as' => 'logout', 'uses' => 'backend\DashboardController@getLogout'));
Route::post('admin', 'backend\DashboardController@postLogin');

Route::get('/{id}','backend\DashboardController@notFound');

Route::group(['middleware'=>['auth']],function(){
    Route::get('admin/expensestype', 'backend\DashboardController@getExpenses');
    Route::post('admin/expensestype', 'backend\DashboardController@postExpenses');
    Route::get('admin/logout', 'backend\DashboardController@getLogout');

    Route::get('admin/{user_id}/dashboard','backend\DashboardController@index');
    Route::get('admin/dashboard','backend\DashboardController@index');
    Route::resource('admin/user','backend\UserController');
    Route::resource('admin/installment','backend\DhaInstallmentController');
    Route::resource('admin/installmentservice','backend\ServiceInstallmentController');
    Route::get('admin/serviceinvoice/{id}','backend\ServiceInstallmentController@viewinvoice');
    Route::post('admin/installment/{id}','backend\DhaInstallmentController@create');
    Route::post('admin/installmentservice/{id}','backend\ServiceInstallmentController@create');
    Route::post('admin/installmentservice/{id}','backend\ServiceInstallmentController@create');
    Route::delete('admin/installmentservice/{id}','backend\ServiceInstallmentController@destroy');
    Route::post('admin/installment','backend\DhaInstallmentController@store');
    Route::delete('admin/installment/{id}','backend\DhaInstallmentController@destroy');
    Route::get('admin/viewinvoice/{id}','backend\DhaInstallmentController@viewinvoice');
    // show report
    Route::post('admin/dhainstallment','backend\DHAController@createdhainstallment');

    Route::get('admin/edit/{id}','backend\DhaController@edit');
    Route::get('admin/editservicecharge/{id}','backend\ServiceChargeController@edit');
    Route::post('admin/json','backend\JsonController@json');
    Route::resource('admin/service_charge','backend\ServiceChargeController');


    Route::resource('admin/cash_in','backend\cash_inController');

    Route::resource('admin/cash_out','backend\CashOutController');

    Route::resource('admin/dha','backend\DHAController');
    Route::get('admin/dhashow/{id}','backend\DHAController@show');
    Route::resource('admin/enquiry','backend\EnquiryController');
    Route::resource('admin/enquirybythem','backend\EnquiryByThemController');
    Route::resource('admin/enquiryinoffice','backend\EnquiryInOFficeController');
    Route::get('admin/dhainvoice','backend\InvoiceController@dhainvoice');
    Route::get('admin/serviceinvoice','backend\InvoiceController@serviceinvoice');
    Route::resource('admin/reminder','backend\ReminderController');
    Route::resource('admin/service','backend\ServiceController');
    Route::resource('admin/student','backend\StudentController');
    Route::resource('admin/transaction','backend\TransactionController');
    Route::resource('admin/offer','backend\OfferController');
    Route::resource('admin/status','backend\StatusController');
    Route::get('admin/viewstatus','backend\ViewStatusController@show');
    Route::get('admin/statuss','backend\StatusController@createdhastatus');
    Route::get('admin/dhastatus','backend\StatusController@createdhastatus');
    Route::post('admin/dhastatuss','backend\StatusController@postdhastatus');
    // Route::resource('admin/dataflow','DataFlowStatusController');
    Route::resource('admin/dataflow','backend\DataFlowStatusController');
    Route::get('admin/dataflowform','backend\DataFlowStatusController@create');
    Route::post('admin/dataflowform','backend\DataFlowStatusController@store');
    Route::resource('admin/examstatus','backend\ExamStatusController');
    Route::get('admin/examstatusform','backend\ExamStatusController@create');
    Route::post('admin/examstatusform','backend\ExamStatusController@store');
    Route::post('admin/contact','backend\OfferController@postOffer');
// CanditatesREport

    Route::resource('admin/candidates_report','backend\CandidatesReportController'); 

   


    // newsletter
    Route::get('admin/news','backend\NewsLetterController@contact');
    Route::post('admin/news','backend\NewsLetterController@postcontact');
    // CMS
    Route::get('admin/cms','backend\cmsController@index');
    Route::get('updatePassword', 'backend\DashboardController@updatePassword');
    Route::get('admin/{username}/profile', 'backend\DashboardController@profile');
    Route::post('/profilepost', 'backend\DashboardController@updatePassword')->name('profilepost');
    Route::post('/profilepost/{id}', 'backend\DashboardController@editInfo');
    Route::post('updateProfile','backend\DashboardController@updateProfile');
    // show report
    Route::post('admin/report','backend\DashboardController@getReport');
    Route::post('admin/nepalicalender','backend\DashboardController@nepalidate');
    Route::post('admin/nepali','backend\DashboardController@nepali');
    Route::post('admin/englishDate','backend\DashboardController@englishDate');
    Route::post('admin/nepalidate2','backend\DashboardController@nepaliDate2');
    Route::post('admin/englishdate2','backend\DashboardController@englishDate2');
    Route::get('admin/{id}','backend\DashboardController@notFound');
    Route::get('admin/{id}/{ids}','backend\DashboardController@notFound');



});

/*Route::get('/', funcbtion () {
    return view('welcome');

live/app/Reminder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;

class Reminder extends Model
{
 protected $fillable=['subject','date','message','nepali_date','status','user_id'];

    public function count_remainder(){
        $user_id=Auth::user()->id;
        return $this->where('user_id',$user_id)->where('status','1')->count();
    }
    public function all_remainder(){
        $user_id=Auth::user()->id;
        return $this->where('user_id',$user_id)->where('status','1')->get();
    }
}

live/app/Http/Controllers/backend/ReminderController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Reminder;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\backend\DateConverterController;
class ReminderController extends Controller
{
	public function __construct( DateConverterController $nep_date){
		$this->nep_date = $nep_date;
	}
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private function convert_to_eng($nepali_date){
    	$nepali=$nepali_date;
    	$nepali_temp=explode('-', $nepali);
    	$nepali_year=$nepali_temp[0];
    	$nepali_month=$nepali_temp[1];
    	$nepali_day=$nepali_temp[2];
    	$eng_temp=$this->nep_date->nep_to_eng($nepali_year,$nepali_month,$nepali_day);
    	$eng_year=$eng_temp['year'];
    	$eng_month=$eng_temp['month'];
    	$eng_day=$eng_temp['date'];
    	$eng_date=$eng_year.'-'.$eng_month.'-'.$eng_day;
    	return $eng_date;
    }
    public function index()
    {
    	$reminders = Reminder::all();

    	return view('officio.reminder.index',compact('reminders'))->with('title','Reminder');
    }
    /**Griffith 
     * Show the form for creating a new resource.
     *ResponseC
     * @return \Illuminate\Http\
     */
    public function create()
    {
    	return view('officio.reminder.create')->with('title','Create Griffith reminder');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    	$nepali_dates = $request->date;
       // $nepali_date=strtotime('$nepali_dates');
       // dd($nepali_date);
    	$this->validate($request, [
    		'subject' => 'required',
    		'message' => 'required',

    		]);
    	$input = $request->all();
    	$nepali_date=$request->nepali_date;
    	$eng_date=$this->convert_to_eng($nepali_date);
    	$reminder=new Reminder;
        $reminder->user_id=Auth::user()->id;
    	$reminder->subject=$request->subject;
    	$reminder->date=$eng_date;
    	$reminder->nepali_date=$request->nepali_date;
    	$reminder->message=$request->message;     
    	$reminder->status=$request->status;
    	$result=$reminder->save();



    	session()->flash('message', 'Reminder Created.');
    	return redirect('admin/reminder');
        // }

    }



    public function show($id)
    {
        $reminder = Reminder::find($id);
        $reminder->status='0';
        $reminder->update();
        return view('officio.reminder.show',compact('reminder'))->with('title','Show Griffith Reminder');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
    	$reminder = Reminder::find($id);
    	return view('officio.reminder.edit',compact('reminder'))->with('title','Edit Griffith Reminder');
    }

    /**
     * Update the specified rescashOutource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    	$this->validate($request, [

    		'subject' => 'required',
    		'message' => 'required',

    		]);

    	$input = $request->all();

    	$nepali_date=$request->nepali_date;
    	$eng_date=$this->convert_to_eng($nepali_date);

    	$reminder = Reminder::find($id);
    	$reminder->subject=$request->subject;
    	$reminder->date=$eng_date;
    	$reminder->nepali_date=$request->nepali_date;
    	$reminder->message=$request->message;
    	
    	$reminder->status=$request->status;
        // $result=$reminder->save();
    	$reminder->update();
 
    	session()->flash('message', 'Griffith Reminder Updated.');
    	return redirect('admin/reminder');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    	if(!request()->ajax()){
    		return false;
    	}

    	Reminder::find($id)->delete();


    	session()->flash('message', 'Griffith Reminder Deleted.');

    	return response()->json(array(
    		'status' => 'success',
    		));
    }
}

live/resources/views/officio/reminder/create.blade.php
@extends('officio.main')
@section('title','add Griffith Reminder')
@section('content')
{{----}}
<script type="text/javascript" src="{{URL::to('js/nepalidatepicker/nepali.datepicker.v2.2.min.js')}}"></script>
<link rel="stylesheet" type="text/css" href="{{URL::to('js/nepalidatepicker/nepali.datepicker.v2.2.min.css')}}" />

<section class="content-header">
    <h1>
        Contact information
    </h1>
</section>
@include('officio.flash.message')

<section class="content">
   <div class="row">
    <div class="col-md-12">

        {{--@include('flash.message')--}}
        {{--@include('errors.list')--}}

        
        <div class="box box-info">
            
            <div class="box-body">
                <div class="row">
                  
                 <div class="col-md-8">
                    {{ Form::open(['url'=>'admin/reminder', 'method'=>'POST', 'class' => 'form-horizontal','enctype'=>'multipart/form-data' ]) }}
                    @include('officio.reminder.form')
                    <div class="text-right border-top">
                        <button type="submit" class="btn btn-warning">Send</button>
                    </div>
                    {{ form::close() }}
                </div>
            </div>
        </div>
    </div>


</div>
<script>
    $('#nepaliDate6').nepaliDatePicker({
      npdMonth: true,
      npdYear: true,
      npdYearCount: 10 
  });

    
</script>
<script>
    $(document).ready(function(){
        $("p").mouseover(function(){
            $("p").css("background-color", "yellow");
        });
        
        $("#btn").click(function(){
            $("p").mouseover();
        });  
        
    });
</script>
</section>
@stop

live/resources/views/officio/reminder/edit.blade.php
@extends('officio.main')


@section('content')
{{----}}
        <!-- Content Header (Pag header) -->
<section class="content-header">
    <h1>
         Edit Reminder  
    </h1>
</section>
@include('officio.flash.message')

<section class="content">
    {!! Form::model($reminder, [
        'route' => ['reminder.update', $reminder->id],
        'class' => 'form-horizontal',
        'method'=> 'PUT'
    ])
!!}

    <div class="row">
        <div class="col-md-10">
              @include('officio.reminder.form')
        </div>
    </div>

    <div class="text-right border-top">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>



    {!! Form::close() !!}

</section>
@stop

live/resources/views/officio/reminder/form.blade.php
<div class="box-body">
 <div class="form-group" {{ $errors->has('subject') ? ' has-error' : '' }}>
    <label for="subject" class="col-sm-2 control-label">Subject:<span class=help-block"
        style="color: #b30000">&nbsp;* </span></label>

        <div class="col-sm-10">
          {!! Form::text('subject', null , ['class'=> 'form-control', 'placeholder' => ' Subject', 'id'=>"subject"]) !!}

          @if ($errors->has('subject'))
          <span class="help-block">
            <strong> {{ $errors->first('subject') }}</strong>
        </span>
        @endif

    </div>
</div>

<div class="form-group" {{ $errors->has('nepali_date') ? ' has-error' : '' }}>
    <label for="nepali_date" class="col-sm-2 control-label">Date:<span class=help-block"
        style="color: #b30000">&nbsp;* </span></label>

        <div class="col-sm-10">
           {!! Form::text('nepali_date', null , ['class'=> 'form-control', 'placeholder' => ' Date', 'id'=>'nepaliDate6']) !!}

            @if ($errors->has('nepali_date'))
            <span class="help-block">
                <strong> {{ $errors->first('nepali_date') }}</strong>
            </span>
            @endif

        </div>
    </div>


    <div class="form-group" {{ $errors->has('message') ? ' has-error' : '' }}>
    <label for="message" class="col-sm-2 control-label">Message:<span class=help-block"
            style="color: #b30000">&nbsp;* </span></label>

            <div class="col-sm-10">
           

  {!! Form::textarea('message', null , ['class'=> 'form-control ckeditor', 'placeholder' => ' Message', 'id'=>'message']) !!}
               @if ($errors->has('message'))
               <span class="help-block">
               <strong> {{ $errors->first('message') }}</strong>
            </span>
            @endif

        </div>
    </div>

   


  <div class="form-group">
    {{Form::label('status','Status:',['class'=>'col-sm-2 control-label'])}}
        <div class="col-sm-8">
                    {{Form::radio('status',"1","1")}}{{Form::label('1','Active')}}
                    {{Form::radio('status',"0")}}{{Form::label('0','Inactive')}}


        </div>
    </div>
</div>

live/resources/views/officio/reminder/index.blade.php
@extends('officio.main')
@section('title','Reminder')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>

     <span>
        <a href="{{ url('admin/reminder/create') }}">
            <button type="button" class="btn btn-success" id="viewbtn">
                Create Reminder
            </button>
        </a>
    </span>
</h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">

            @include('officio.flash.message')

            <div class="box">
                <div class="box-body">
                    <div class="table-reponsive">
                        <table id="example1" class="table table-bordered table-striped user-list">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Subject</th>
                                    <th>Date</th>
                                    <th>Message</th>



                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i=1;
                                ?>
                                @foreach($reminders as $type)
                                <tr>
                                    <td>{{ $i++ }}</td>

                                    <td>{{ $type->subject }}</td>
                                    <td>{{ $type->nepali_date}}</td>
                                    <td><?php echo $type->message; ?></td>




                                    <td>
                                        @if($type->status == 1)
                                        Active
                                        @else
                                        InActive
                                        @endif
                                    </td>

                                    <td>

                                        <a type="button" type="button" class="btn btn-primary btn-sm"
                                        href="{{ route('reminder.edit', array($type->id)) }}">
                                        <i class="flaticon-edit"></i>
                                    </a>
                                    <a type="button" type="button" class="btn btn-success btn-sm"
                                        href="{{ route('reminder.show', array($type->id)) }}">
                                        <i class="fa fa-eye"></i>
                                    </a>

                                    <form action="{{ route('reminder.destroy', array($type->id)) }}"
                                      method="DELETE" class="delete-user-form">
                                      {!! csrf_field() !!}

                                      <button type="submit" class="btn btn-sm btn-danger">
                                        <i class="flaticon-delete-button"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    </tbody>

                    @endforeach
                </table>
            </div>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</div><!-- /.col -->

</div><!-- /.row -->
</section><!-- /.content -->

<script>
    $(function () {
        $('#example1').DataTable({
            "pageLength": 100,
            "dom": '<"top"pfl<"clear">>rt<"bottom"p<"clear">>'
        });
    });
</script>

@stop

live/resources/views/officio/reminder/show.blade.php
@extends('officio.main')


@section('content')
{{----}}
<link rel="stylesheet" href="{{URL::to('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css')}}">
<script src="{{URL::to('https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js')}}"></script>
<script src="{{URL::to('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js')}}"></script>
<!-- Content Header (Pag header) -->
<section class="content-header">
  <h1>
    Reminder<a href="{{URL::to('/admin/reminder')}}"  class="btn btn-success" id="viewbtn">
    View All
  </a>
</h1>
</section>

<section class="content">
<!-- <div class="timeline-item">
                <span class="time"><i class="fa fa-clock-o"></i> {{$reminder->date}}</span>

                <h3 class="timeline-header">{{$reminder->subject}}</h3>

                <div class="timeline-body">
                 {!!$reminder->message!!}
                </div>

              </div>

    <div class="row"> {!!$reminder->message!!}
        <div class="col-md-10">

        </div>
      </div> -->
  <div class="panel panel-info">
      <div class="panel-heading"> <span class="time"><i class="fa fa-clock-o"></i> {{$reminder->date}}</span></div>
      <div class="panel-body">{{$reminder->subject}}</div>
      <div class="panel-body">{!!$reminder->message!!}</div>
  
  </div>
    </section>
   
   
 
@stop